In [1]:
import numpy as np
print(np.__version__)

2.4.6


In [2]:
import numpy as np
import numpy as np

arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [3]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np

print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
import numpy as np

print(np.ones((2,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
import numpy as np

print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
import numpy as np

print(np.arange(0, 10, 2))

[0 2 4 6 8]


In [8]:
import numpy as np

print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


In [9]:
import numpy as np

print(np.random.rand(3,2))

[[0.92317042 0.77501321]
 [0.42948235 0.42578484]
 [0.01132761 0.2631998 ]]


In [10]:
import numpy as np

print(np.random.randn(3,2))

[[-1.6702543  -0.9092626 ]
 [ 0.47070488  0.30392971]
 [ 0.31607771  1.14364147]]


In [11]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [12]:
import numpy as np

a = np.array([1, 2, 3])

print(a + 5)

[6 7 8]


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4])

np.save("array.npy", arr)

loaded_arr = np.load("array.npy")

print(loaded_arr)

[1 2 3 4]


In [14]:
import pandas as pd

print(pd.__version__)

ModuleNotFoundError: No module named 'pandas'